alertmanager:
  ingress:
    enabled: true
    hosts:
    - alertmanager.local
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
    
grafana:
  ingress:
    enabled: true
    hosts:
    - grafana.local
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
  adminPassword: password
  

prometheus:
  ingress:
    enabled: true
    hosts:
    - prometheus.local
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous