alertmanager:
  ingress:
    enabled: true
    hosts:
    - alertmanager.local
    
grafana:
  ingress:
    enabled: true
    hosts:
    - grafana.local
  adminPassword: password

prometheus:
  ingress:
    enabled: true
    hosts:
    - prometheus.local