version: '3'

tasks:
  tools:install-k3d:
    cmds:
    - wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
  create-cluster:
    vars:
      CLUSTER_NAME: "{{ .CLUSTER_NAME }}"
    env:
      K3D_FIX_DNS: 1
    cmds:
      - task: delete-cluster
        vars: 
          CLUSTER_NAME: "{{ .CLUSTER_NAME }}"
      - >
        k3d cluster create {{ .CLUSTER_NAME }} 
        --servers 1 
        -p "80:80@loadbalancer" 
        -p "443:443@loadbalancer" 
        -p "127.0.0.1:53:32220/tcp@server:0" 
        -p "127.0.0.1:53:32220/udp@server:0" 
        --k3s-arg "--default-local-storage-path=/k3s-pv@servers:*" 
        --volume /k3s:/k3s@all 
        --volume /k3s-pv:/k3s-pv@all
        # --k3s-arg --disable=traefik@server:0 
        # --k3s-arg --disable=local-storage@server:0
      - task: install-coredns

  install-coredns:
    cmds:
    - helm repo add coredns https://coredns.github.io/helm
    - helm upgrade --install -n tools --create-namespace coredns coredns/coredns --values localcluster/values/coredns.yaml
    - kubectl -n tools apply -f localcluster/manifests/coredns-service.yaml

  delete-cluster:
    vars:
      CLUSTER_NAME: "{{ .CLUSTER_NAME }}"
    cmds:
      - >
        k3d cluster delete {{ .CLUSTER_NAME }} 
