apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources: {}
  sourceRepos:
  - '*'
status: {}
