apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-bundle
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: apps
    server: https://kubernetes.default.svc
  project: apps
  source:
    path: Helm/Charts/argo-apps
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  syncPolicy:
    automated: {}