{{- if .Values.enabled.octant -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: octant
spec:
  destination:
    namespace: homelab
    server: {{ .Values.spec.destination.server }}
  project: apps
  source:
    path: Helm/Charts/octant
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
{{ end }}
