{{- if .Values.enabled.strimzi -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi
spec:
  destination:
    namespace: strimzi
    server: {{ .Values.spec.destination.server }}
  project: apps
  source:
    path: Helm/Charts/strimzi-kafka-operator
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
      - values.yaml 
      - values-custom.yaml
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
{{ end }}
