apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.traefikHost }}
spec:
  dnsNames:
    - {{ .Values.traefikHost }}
  secretName: {{ .Values.traefikHost }}
  issuerRef:
    name: {{ .Values.certificateIssuer }}
    kind: ClusterIssuer