{{- $app := .Release.Name -}}
{{- $component := "web" -}}
{{- $name := printf "%s-%s" $app $component -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    app: "{{ $app }}"
    component: "{{ $component }}"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: "{{ $app }}"
    component: "{{ $component }}"