apiVersion: v1
kind: Service
metadata:
  name: test-mesh
  namespace: test-mesh
  annotations:
    80.service.kuma.io/protocol: http
spec:
  selector:
    app: test-mesh
  ports:
  - port: 80
    targetPort: 80
