argo-cd:
  server:
    extraArgs:
    - --insecure
    ingress:
      enabled: false
      hosts:
      - argocd.local
      paths:
      - "/"

certificateIssuer: homelab-cluster-issuer

enabled:
  metricsServer: false
  vault: false
  strimzi: false
  kafka: false
  prometheus: false
  vpa: false
  kuma: false
  kubernetesDashboard: false
  kubeResourceReport: false
  octant: false
  heimdall: true
  certManager: true
  traefik: true

spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/krzwiatrzyk/homelab.git
    targetRevision: HEAD

installCRDs: true

apps:
- name: dapr
  chartRepo: https://dapr.github.io/helm-charts/
  values: |

