{{- if .Values.enabled.certManager -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: {{ .Values.spec.destination.server }}
  project: apps
  source:
    path: Helm/Charts/cert-manager
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
{{ end }}
