{{- if .Values.enabled.kubeResourceReport -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-resource-report
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: {{ .Values.spec.destination.server }}
  project: apps
  source:
    path: Helm/Charts/kube-resource-report
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
{{ end }}
