{{- if .Values.enabled.kuma -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuma
spec:
  destination:
    namespace: {{ .Release.Namespace }}
    server: {{ .Values.spec.destination.server }}
  project: apps
  source:
    path: Helm/Charts/kuma
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jsonPointers:
    - /webhooks
{{ end }}
