{{ if and (eq .Values.ingressController "traefik") (.Values.enabled.kuma) }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kuma.local
spec:
  dnsNames:
    - kuma.local
  secretName: kuma.local
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
{{ end }}