{{ if eq .Values.ingressController "traefik" }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-ingress-route
  namespace: default
spec:
  entryPoints:
  - traefik
  routes:
    - kind: Rule
      match: Host(`traefik.local`)
      services:
      - kind: TraefikService
        name: api@internal
  tls:
    secretName: traefik.local
{{ end }}
  