install-kubernetes-dashboard:
	kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.4.0/aio/deploy/recommended.yaml

uninstall-kubernetes-dashboard:
	kubectl delete -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.4.0/aio/deploy/recommended.yaml

install-skooner-dashboard:
	kubectl apply -f https://raw.githubusercontent.com/skooner-k8s/skooner/master/kubernetes-skooner.yaml

uninstall-skooner-dashboard:
	kubectl delete -f https://raw.githubusercontent.com/skooner-k8s/skooner/master/kubernetes-skooner.yaml

