apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: https-cert
  namespace: vault
  annotations:
    "helm.sh/hook": pre-install
spec:
  dnsNames:
  - vault.local
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: test-selfsigned
  secretName: https-cert
