ingressController: traefik
enabled:
  metricsserver: false
  vault: false
  strimzi: false
  kafka: false
  prometheus: false
  vpa: true
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/krzwiatrzyk/homelab.git
    targetRevision: HEAD